- hosts: rpi
  remote_user: pi
  become: yes

  tasks:
  - name: Update packages
    apt:
      update_cache: yes
      cache_valid_time: 3600

  - name: Install aptitude
    apt:
      name: aptitude
      state: latest

  - name: Install docker prereqs
    apt:
      name: "{{ packages }}"
      state: latest
    vars:
      packages:
        - apt-transport-https
        - ca-certificates
        - software-properties-common

  - name: Add docker GPG Key
    apt_key:
      url: https://download.docker.com/linux/raspbian/gpg

  - name: Add docker repo
    apt_repository:
      repo: deb [arch=armhf] https://download.docker.com/linux/raspbian stretch stable

  - name: Install docker-ce
    apt:
      name: "{{ packages }}"
      # state: latest
    vars:
      packages:
        - docker-ce
        - docker-ce-cli
        - containerd.io
  
  # Required to manage docker swarm via Ansible
  - name: Install python docker sdk
    pip:
      name: docker
