{
 "title": "Docker Overview",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "Host", "query": "rpi01,rpi02" }
  ]
 },
 "panels": [
  {
   "title": "Host CPU Usage",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    { "expr": "cpu_usage_idle * -1 + 100", "legendFormat": "{{ host }}" }
   ]
  },
  {
   "title": "Host Memory Usage",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    { "expr": "mem_used_percent", "legendFormat": "{{ host }}" }
   ]
  },
  { "title": "$Host", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 }, "repeat": "Host" },
  {
   "title": "Running",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 0, "y": 7 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "docker_n_containers_running{engine_host=\"$Host\"}"
    }
   ]
  },
  {
   "title": "Container CPU Usage",
   "type": "graph",
   "gridPos": { "h": 6, "w": 11, "x": 2, "y": 7 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "docker_container_cpu_usage_percent{engine_host=\"$Host\"}",
     "legendFormat": "{{ com_docker_swarm_service_name }}"
    }
   ]
  },
  {
   "title": "Container Memory Usage",
   "type": "graph",
   "gridPos": { "h": 6, "w": 11, "x": 13, "y": 7 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "docker_container_mem_usage_percent{engine_host=\"$Host\"}",
     "legendFormat": "{{ com_docker_swarm_service_name }}"
    }
   ]
  },
  {
   "title": "Paused",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 0, "y": 9 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "docker_n_containers_paused{host=\"$Host\"}"
    }
   ]
  },
  {
   "title": "Stopped",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 0, "y": 11 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "docker_n_containers_stopped{engine_host=\"$Host\"}"
    }
   ]
  },
  { "title": "$Host", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": "Running",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 0, "y": 14 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "docker_n_containers_running{engine_host=\"$Host\"}"
    }
   ]
  },
  {
   "title": "Container CPU Usage",
   "type": "graph",
   "gridPos": { "h": 6, "w": 11, "x": 2, "y": 14 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "docker_container_cpu_usage_percent{engine_host=\"$Host\"}",
     "legendFormat": "{{ com_docker_swarm_service_name }}"
    }
   ]
  },
  {
   "title": "Container Memory Usage",
   "type": "graph",
   "gridPos": { "h": 6, "w": 11, "x": 13, "y": 14 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "docker_container_mem_usage_percent{engine_host=\"$Host\"}",
     "legendFormat": "{{ com_docker_swarm_service_name }}"
    }
   ]
  },
  {
   "title": "Paused",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 0, "y": 16 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "docker_n_containers_paused{host=\"$Host\"}"
    }
   ]
  },
  {
   "title": "Stopped",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 0, "y": 18 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "docker_n_containers_stopped{engine_host=\"$Host\"}"
    }
   ]
  }
 ]
}