{
 "title": "Plex Overview",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "Host", "query": "holocron" }
  ]
 },
 "panels": [
  {
   "title": "CPU Usage",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "cpu_usage_idle{host=~\"$Host\"} * -1 + 100"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 0 },
   "targets": [
    {
     "expr": "mem_used_percent{host=~\"$Host\"}"
    }
   ]
  },
  {
   "title": "Primary Disk Usage",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 6, "y": 0 },
   "targets": [
    {
     "expr": "disk_used_percent{host=\"$Host\",path=\"/\"}",
     "legendFormat": "{{ path }}"
    }
   ]
  },
  {
   "title": "Data Disk Usage",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 9, "y": 0 },
   "targets": [
    {
     "expr": "disk_used_percent{host=\"$Host\",path=\"/mnt/data\"}",
     "legendFormat": "{{ path }}"
    }
   ]
  },
  {
   "title": "Uploads Disk Usage",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "disk_used_percent{host=\"$Host\",path=\"/mnt/uploads\"}",
     "legendFormat": "{{ path }}"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 0, "y": 5 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "system_uptime{host=\"$Host\"}"
    }
   ]
  },
  {
   "title": "Download Rate",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 2, "y": 5 },
   "format": "Bps",
   "valueName": "current",
   "targets": [
    {
     "expr": "rate(net_bytes_recv{host=\"$Host\",interface=\"enp1s0\"}[5m])"
    }
   ]
  },
  {
   "title": "Upload Rate",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 4, "y": 5 },
   "format": "Bps",
   "valueName": "current",
   "targets": [
    {
     "expr": "rate(net_bytes_sent{host=~\"$Host\",interface=\"enp1s0\"}[5m])"
    }
   ]
  },
  {
   "title": "Primary Disk Available",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 6, "y": 5 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "disk_free{host=\"$Host\",path=\"/\"}",
     "legendFormat": "{{ host }}"
    }
   ]
  },
  {
   "title": "Data Disk Available",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 9, "y": 5 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "disk_free{host=\"$Host\",path=\"/mnt/data\"}",
     "legendFormat": "{{ host }}"
    }
   ]
  },
  {
   "title": "Uploads Disk Available",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 12, "y": 5 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "disk_free{host=\"$Host\",path=\"/mnt/uploads\"}",
     "legendFormat": "{{ host }}"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "cpu_usage_idle{host=~\"$Host\"} * -1 + 100",
     "legendFormat": "{{ host }}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "mem_used_percent{host=~\"$Host\"}",
     "legendFormat": "{{ host }}"
    }
   ]
  },
  {
   "title": "Bandwidth Usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "rate(net_bytes_recv{host=\"$Host\",interface=\"enp1s0\"}[5m])",
     "legendFormat": "Download"
    },
    {
     "expr": "rate(net_bytes_sent{host=~\"$Host\",interface=\"enp1s0\"}[5m])",
     "legendFormat": "Upload"
    }
   ]
  }
 ]
}