{
 "title": "RPi Overview",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "Host", "query": "rpiman,rpi01,rpi02" }
  ]
 },
 "panels": [
  { "title": "$Host", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "Host" },
  {
   "title": "$Host CPU Temp",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "(rpi_cpu_temp{host=~\"$Host\"} / 1000 * 9/5) + 32"
    }
   ]
  },
  {
   "title": "$Host CPU Usage",
   "type": "graph",
   "gridPos": { "h": 5, "w": 10, "x": 4, "y": 1 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "cpu_usage_idle{host=~\"$Host\"} * -1 + 100"
    }
   ]
  },
  {
   "title": "$Host Memory Usage",
   "type": "graph",
   "gridPos": { "h": 5, "w": 10, "x": 14, "y": 1 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "mem_used_percent{host=~\"$Host\"}"
    }
   ]
  },
  { "title": "$Host", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  {
   "title": "$Host CPU Temp",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "(rpi_cpu_temp{host=~\"$Host\"} / 1000 * 9/5) + 32"
    }
   ]
  },
  {
   "title": "$Host CPU Usage",
   "type": "graph",
   "gridPos": { "h": 5, "w": 10, "x": 4, "y": 7 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "cpu_usage_idle{host=~\"$Host\"} * -1 + 100"
    }
   ]
  },
  {
   "title": "$Host Memory Usage",
   "type": "graph",
   "gridPos": { "h": 5, "w": 10, "x": 14, "y": 7 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "mem_used_percent{host=~\"$Host\"}"
    }
   ]
  },
  { "title": "$Host", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 } },
  {
   "title": "$Host CPU Temp",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 13 },
   "targets": [
    {
     "expr": "(rpi_cpu_temp{host=~\"$Host\"} / 1000 * 9/5) + 32"
    }
   ]
  },
  {
   "title": "$Host CPU Usage",
   "type": "graph",
   "gridPos": { "h": 5, "w": 10, "x": 4, "y": 13 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "cpu_usage_idle{host=~\"$Host\"} * -1 + 100"
    }
   ]
  },
  {
   "title": "$Host Memory Usage",
   "type": "graph",
   "gridPos": { "h": 5, "w": 10, "x": 14, "y": 13 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "mem_used_percent{host=~\"$Host\"}"
    }
   ]
  }
 ]
}