---
- name: add influxdb key
  apt_key:
    url: https://repos.influxdata.com/influxdb.key

- name: add influxdata repo
  apt_repository:
    repo: deb https://repos.influxdata.com/debian stretch stable

- name: install telegraf
  apt:
    name: telegraf

- name: copy config
  copy:
    src: telegraf.conf
    dest: /etc/telegraf/telegraf.conf

- name: copy rpi thermal script
  copy:
    src: rpi-temp.sh
    dest: /usr/local/bin/rpi-temp.sh

- name: start telegraf
  service:
    name: telegraf
    state: restarted

- name: add telegraf user to docker group
  user:
    name: telegraf
    groups: docker

- name: start telegraf
  service:
    name: telegraf
    state: restarted