---
- name: add influxdb key
  apt_key:
    url: "{{ influxdb_key }}"

- name: add influxdata repo
  apt_repository:
    repo: "{{ influxdb_repo }}"

- name: install telegraf
  apt:
    name: telegraf

- name: copy config
  copy:
    src: telegraf.conf
    dest: "{{ telegraf_dest }}"
  notify: restart telegraf

- name: copy rpi thermal script
  copy:
    src: rpi-temp.sh
    dest: "{{ thermal_script_dest }}"
  notify: restart telegraf

- name: add telegraf user to docker group
  user:
    name: telegraf
    groups: docker
  notify: restart telegraf
