- name: deploy clintcolding.com swarm service
  hosts: rpi01
  remote_user: pi
  become: yes
  
  vars_files:
    - ~/git/HomeLab/vault.yml

  vars:
    ansible_ssh_pass: "{{ remote_pass }}"

  tasks:
    - name: create clintcolding_web swarm service
      docker_swarm_service:
        name: clintcolding_web
        image: clintcolding/clintcolding_web
        networks:
          - traefik
        replicas: 2
        labels:
          #---- 80 Entry ----#
          traefik.http.routers.clintcolding_web.rule: "Host(`clintcolding.com`)"
          traefik.http.routers.clintcolding_web.entrypoints: "web"
          traefik.http.routers.clintcolding_web.middlewares: "redirect"
          #---- 443 Entry ----#
          traefik.http.routers.clintcolding_websecure.rule: "Host(`clintcolding.com`)"
          traefik.http.routers.clintcolding_websecure.entrypoints: "websecure"
          #---- Create the middleware "redirect" used on 80 entry ----#
          traefik.http.middlewares.redirect.redirectscheme.scheme: "https"
          #---- Expose container port 80 ----#
          traefik.http.services.clintcolding_web-service.loadbalancer.server.port: "80"
          #---- ACME config for websecure router ----#
          traefik.http.routers.clintcolding_websecure.tls.certresolver: "httpchallenge"
          
