- name: deploy grafana and prometheus swarm services
  hosts: rpi01
  remote_user: pi
  become: yes
  
  vars_files:
    - ~/git/HomeLab/vault.yml

  vars:
    ansible_ssh_pass: "{{ remote_pass }}"

  tasks:
    - name: create grafana volume
      docker_volume:
        name: grafana-data

    - name: copy prom config
      copy:
        src: ~/git/HomeLab/files/prometheus.yml
        dest: /etc/prometheus.yml

    - name: create grafana swarm service
      docker_swarm_service:
        name: grafana
        image: grafana/grafana:6.3.5
        replicas: 1
        networks:
          - traefik
        placement:
          constraints:
            - node.hostname == rpi02
        env:
          GF_INSTALL_PLUGINS: grafana-piechart-panel
        labels:
          traefik.http.routers.grafana.rule: "Host(`grafana.thecoldings.com`)"
          traefik.http.services.grafana-service.loadbalancer.server.port: "3000"
          traefik.http.routers.grafana.entrypoints: "websecure"
          traefik.http.routers.grafana.tls.certresolver: "httpchallenge"
        mounts:
          - source: grafana-data
            target: /var/lib/grafana/
            type: volume

    - name: create prometheus swarm service
      docker_swarm_service:
        name: prom
        image: prom/prometheus:v2.12.0
        replicas: 1
        networks:
          - traefik
        placement:
          constraints:
            - node.hostname == rpi01
        labels:
          traefik.http.routers.prom.rule: "Host(`prom.thecoldings.com`)"
          traefik.http.services.prom-service.loadbalancer.server.port: "9090"
          traefik.http.routers.prom.entrypoints: "websecure"
          traefik.http.routers.prom.tls.certresolver: "httpchallenge"
        mounts:
          - source: /etc/prometheus.yml
            target: /etc/prometheus/prometheus.yml
            type: bind