- name: deploy portainer server and agents
  hosts: rpi01
  remote_user: pi
  become: yes
  
  vars_files:
    - ~/git/HomeLab/vault.yml

  vars:
    ansible_ssh_pass: "{{ remote_pass }}"

  tasks:
    - name: create portainer agent network
      docker_network:
        name: portainer_agent_network
        driver: overlay
        attachable: yes

    - name: create portainer agent swarm service
      docker_swarm_service:
        name: portainer_agent
        image: portainer/agent
        mode: global
        networks:
          - portainer_agent_network
        labels:
          traefik.http.routers.grafana.rule: "Host(`grafana.thecoldings.com`)"
          traefik.http.services.grafana-service.loadbalancer.server.port: "3000"
          traefik.http.routers.grafana.entrypoints: "websecure"
          traefik.http.routers.grafana.tls.certresolver: "httpchallenge"
        mounts:
          - source: /var/run/docker.sock
            target: /var/run/docker.sock
            type: bind
          - source: /var/lib/docker/volumes
            target: /var/lib/docker/volumes
            type: bind

    - name: create portainer server swarm service
      docker_swarm_service:
        name: portainer
        image: portainer/portainer
        replicas: 1
        networks:
          - portainer_agent_network
        placement:
          constraints:
            - node.role == manager
        command: -H tcp://tasks.agent:9001 --tlsskipverify
        labels:
          traefik.http.routers.grafana.rule: "Host(`grafana.thecoldings.com`)"
          traefik.http.services.grafana-service.loadbalancer.server.port: "3000"
          traefik.http.routers.grafana.entrypoints: "websecure"
          traefik.http.routers.grafana.tls.certresolver: "httpchallenge"
        mounts:
          - source: grafana-data
            target: /var/lib/grafana/
            type: volume