---
- name: update packages
  apt:
    update_cache: yes
    cache_valid_time: 3600

- name: install docker prereqs
  apt:
    name: "{{ packages }}"
    state: latest
  vars:
    packages:
      - apt-transport-https
      - ca-certificates
      - software-properties-common
      - python-pip

- name: add docker GPG Key
  apt_key:
    url: https://download.docker.com/linux/raspbian/gpg

- name: add docker repo
  apt_repository:
    repo: deb [arch=armhf] https://download.docker.com/linux/raspbian stretch stable
    update_cache: yes

- name: install docker
  apt:
    name: "{{ packages }}"
  vars:
    packages:
      - docker-ce
      - docker-ce-cli
      - containerd.io

- name: install python docker sdk
  pip:
    name: docker

- name: create leader
  docker_swarm:
    state: present
  register: token
  when: role is defined and role == "leader"

- name: add workers
  docker_swarm:
    state: join
    advertise_addr: "{{ ansible_default_ipv4.address }}"
    join_token: "{{ hostvars[groups['docker'][0]]['token']['swarm_facts']['JoinTokens']['Worker'] }}"
    remote_addrs: [ "{{ hostvars[groups['docker'][0]].ansible_default_ipv4.address }}:2377" ]
  when: role is undefined