---
- name: create leader
  docker_swarm:
    state: present
  register: token
  when: role is defined and role == "leader"

- name: add workers
  docker_swarm:
    state: join
    advertise_addr: "{{ ansible_default_ipv4.address }}"
    join_token: "{{ hostvars[groups['docker'][0]]['token']['swarm_facts']['JoinTokens']['Worker'] }}"
    remote_addrs: [ "{{ hostvars[groups['docker'][0]].ansible_default_ipv4.address }}:2377" ]
  when: role is undefined