# This configuration is used to route traffic to a 2nd
# RaspberryPi that isn't part of the Swarm
http:
  routers:
    homeassistant:
      entryPoints:
      - "websecure"
      service: "homeassistant"
      rule: "Host(`ha.thecoldings.com`)"
      tls:
        certResolver: "httpchallenge"
  services:
    homeassistant:
      loadBalancer:
        servers:
          - url: "http://192.168.1.102:8123"