{
 "title": "Traefik",
 "tags": [
  "docker",
  "traefikv2"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "Interval", "query": "1m,5m,10m,15m" }
  ]
 },
 "panels": [
  {
   "title": "Uptime",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 0 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "time() - process_start_time_seconds{job=\"traefik\"}"
    }
   ]
  },
  {
   "title": "Average Response Time",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 5, "x": 4, "y": 0 },
   "targets": [
    {
     "expr": "sum(traefik_entrypoint_request_duration_seconds_sum) / sum(traefik_entrypoint_requests_total) * 1000"
    }
   ]
  },
  {
   "title": "Traefik CPU Usage",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 5, "x": 9, "y": 0 },
   "targets": [
    {
     "expr": "docker_container_cpu_usage_percent{container_name=~\".*traefik.*\"}",
     "legendFormat": "{{ com_docker_swarm_service_name }}"
    }
   ]
  },
  {
   "title": "Traefik Memory Usage",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 5, "x": 14, "y": 0 },
   "targets": [
    {
     "expr": "docker_container_mem_usage_percent{container_name=~\".*traefik.*\"}",
     "legendFormat": "{{ com_docker_swarm_service_name }}"
    }
   ]
  },
  {
   "title": "Return Codes",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 6, "w": 5, "x": 19, "y": 0 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(increase(traefik_entrypoint_requests_total[$Interval])) by (code)",
     "legendFormat": "{{ code }}"
    }
   ]
  },
  {
   "title": "Total Config Reloads",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 2 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "traefik_config_reloads_total", "legendFormat": "{{method}} : {{code}}" }
   ]
  },
  {
   "title": "Reload Failures",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 4 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "traefik_config_reloads_failure_total",
     "legendFormat": "{{method}} : {{code}}"
    }
   ]
  },
  {
   "title": "Requests by Service",
   "type": "graph",
   "gridPos": { "h": 6, "w": 19, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(traefik_service_requests_total[$Interval])) by (service)",
     "legendFormat": "{{ service }}"
    }
   ]
  },
  {
   "title": "Requests by Method",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 6, "w": 5, "x": 19, "y": 6 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(increase(traefik_entrypoint_requests_total[$Interval])) by (method)",
     "legendFormat": "{{ method }}"
    }
   ]
  },
  {
   "title": "Bad Status Codes",
   "type": "graph",
   "gridPos": { "h": 6, "w": 19, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(traefik_service_requests_total{code!=\"200\"}[$Interval])",
     "legendFormat": "{{ code }} : {{ service }}"
    }
   ]
  },
  {
   "title": "Requests by Entrypoint",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 6, "w": 5, "x": 19, "y": 12 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(increase(traefik_entrypoint_requests_total[$Interval])) by (entrypoint)",
     "legendFormat": "{{ entrypoint }}"
    }
   ]
  }
 ]
}