---
- name: set hostname
  command: hostnamectl set-hostname "{{ inventory_hostname }}"

- name: update hostname in /etc/hosts 
  lineinfile:
    dest: /etc/hosts
    regexp: "^127.0.1.1\traspberrypi$"
    line: "127.0.1.1\t{{ inventory_hostname }}"

- name: update packages
  apt:
    update_cache: yes
    cache_valid_time: 3600

- name: install aptitude
  apt:
    name: aptitude
    state: latest