- hosts: rpi01
  remote_user: pi
  become: yes
  
  vars_files:
    - ./vault.yml

  vars:
    ansible_ssh_pass: "{{ remote_pass }}"

  tasks:
  - name: install dependencies
    apt:
      name: "{{ packages }}"
      state: latest
    vars:
      packages:
        - liblttng-ust0
        - libkrb5-3
        - zlib1g
        - libcurl3
        - libssl1.0.2
        - libicu57

  - name: get package
    unarchive:
      src: https://vstsagentpackage.azureedge.net/agent/2.155.1/vsts-agent-linux-arm-2.155.1.tar.gz
      dest: /usr/local/bin
      remote_src: yes
      creates: /usr/local/bin/config.sh