- hosts: rpi
  remote_user: pi
  become: yes
  
  vars_files:
    - ./vault.yml

  vars:
    ansible_ssh_pass: "{{ remote_pass }}"

  tasks:
  - name: set hostname
    command: hostnamectl set-hostname "{{ inventory_hostname }}"

  - name: update /etc/hosts 
    lineinfile:
      dest: /etc/hosts
      regexp: "^127.0.1.1\traspberrypi$"
      line: "127.0.1.1\t{{ inventory_hostname }}"
      state: present

  - name: update packages
    apt:
      update_cache: yes
      cache_valid_time: 3600

  - name: install aptitude
    apt:
      name: aptitude
      state: latest

  - name: install docker prereqs
    apt:
      name: "{{ packages }}"
      state: latest
    vars:
      packages:
        - apt-transport-https
        - ca-certificates
        - software-properties-common

  - name: add docker GPG Key
    apt_key:
      url: https://download.docker.com/linux/raspbian/gpg

  - name: add docker repo
    apt_repository:
      repo: deb [arch=armhf] https://download.docker.com/linux/raspbian stretch stable

  - name: install docker
    apt:
      name: "{{ packages }}"
      # state: latest
    vars:
      packages:
        - docker-ce
        - docker-ce-cli
        - containerd.io
  
  # Required to manage docker swarm via Ansible
  - name: install python docker sdk
    pip:
      name: docker
