- hosts: rpi01
  remote_user: pi
  become: yes
  
  vars_files:
    - ./vault.yml

  vars:
    ansible_ssh_pass: "{{ remote_pass }}"

  tasks:
    - name: copy config
      copy:
        src: ./files/prometheus.yml
        dest: /etc/prometheus.yml

    - name: create grafana swarm service
      docker_swarm_service:
        name: grafana
        image: grafana/grafana
        replicas: 1
        publish:
          - published_port: 3000
            target_port: 3000

    - name: create prometheus swarm service
      docker_swarm_service:
        name: prom
        image: prom/prometheus
        replicas: 1
        publish:
          - published_port: 9090
            target_port: 9090
        mounts:
          - source: /etc/prometheus.yml
            target: /etc/prometheus/prometheus.yml
            type: bind