- hosts: rpi01
  remote_user: pi
  become: yes
  
  vars_files:
    - ~/git/HomeLab/vault.yml

  vars:
    ansible_ssh_pass: "{{ remote_pass }}"

  tasks:
    - name: copy config
      copy:
        src: ~/git/HomeLab/files/prometheus.yml
        dest: /etc/prometheus.yml

    - name: create grafana swarm service
      docker_swarm_service:
        name: grafana
        image: grafana/grafana
        replicas: 1
        networks:
          - traefik
        labels:
          traefik.port: "3000"
          traefik.frontend.rule: "Host:grafana.clint.com"

    - name: create prometheus swarm service
      docker_swarm_service:
        name: prom
        image: prom/prometheus
        replicas: 1
        networks:
          - traefik
        labels:
          traefik.port: "9090"
          traefik.frontend.rule: "Host:prom.clint.com"
        mounts:
          - source: /etc/prometheus.yml
            target: /etc/prometheus/prometheus.yml
            type: bind