- name: install and configure telegraf agent
  hosts: all
  remote_user: pi
  become: yes

  vars_files:
    - ~/git/HomeLab/vault.yml

  vars:
    ansible_ssh_pass: "{{ remote_pass }}"

  tasks:
  - name: update packages
    apt:
      update_cache: yes
      cache_valid_time: 3600

  - name: add influxdb key
    apt_key:
      url: https://repos.influxdata.com/influxdb.key

  - name: add influxdata repo
    apt_repository:
      repo: deb https://repos.influxdata.com/debian stretch stable

  - name: install telegraf
    apt:
      name: telegraf

  - name: copy config
    copy:
      src: ~/git/HomeLab/files/telegraf.conf
      dest: /etc/telegraf/telegraf.conf
  
  - name: copy rpi thermal script
    copy:
      src: ~/git/HomeLab/files/rpi-temp.sh
      dest: /usr/local/bin/rpi-temp.sh

  - name: start telegraf
    service:
      name: telegraf
      state: restarted

  - name: add telegraf user to docker group
    user:
      name: telegraf
      groups: docker