- name: install unifi controller
  hosts: rpiman
  remote_user: pi
  become: yes
  
  vars_files:
    - ~/git/HomeLab/vault.yml

  vars:
    ansible_ssh_pass: "{{ remote_pass }}"

  tasks:
    - name: download unifi controller software
      get_url:
        url: http://dl.ubnt.com/unifi/5.11.50/unifi_sysvinit_all.deb
        dest: /usr/local/src/unifi_sysvinit_all.deb

    - name: update packages
      apt:
        update_cache: yes
        cache_valid_time: 3600

    - name: install java and haveged
      apt:
        name: "{{ packages }}"
        state: latest
      vars:
        packages:
          - openjdk-8-jre-headless
          - haveged

    - name: install unifi controller
      apt:
        deb: /usr/local/src/unifi_sysvinit_all.deb