---
- name: create traefik swarm service
  docker_swarm_service:
    name: traefik
    image: traefik:v2.0
    networks:
      - traefik
    replicas: 1
    args: 
      # Enable API and Dashboard UI
      - "--api"
      - "--api.insecure=true"
      # Enable the Docker provider
      - "--providers.docker"
      - "--providers.docker.swarmmode=true"
      - "--providers.docker.watch"
      # Enable the File provider
      - "--providers.file.directory=/etc/traefik/dynamic"
      # Configure ACME Let's Encrypt
      - "--entryPoints.web.address=:80"
      - "--entryPoints.websecure.address=:443"
      - "--certificatesResolvers.httpchallenge.acme.httpChallenge=true"
      - "--certificatesResolvers.httpchallenge.acme.httpChallenge.entryPoint=web"
      - "--certificatesResolvers.httpchallenge.acme.email=clintcolding@gmail.com"
      - "--certificatesResolvers.httpchallenge.acme.storage=/letsencrypt/acme.json"
      # Enable Prometheus metrics and logging
      - "--metrics.prometheus"
      - "--log"
      - "--accessLog"
    publish:
      - published_port: 80
        target_port: 80
      - published_port: 443
        target_port: 443
      - published_port: 8080
        target_port: 8080
    mounts:
      - source: /var/run/docker.sock
        target: /var/run/docker.sock
        type: bind
      - source: traefik-certs
        target: /letsencrypt
        type: volume
      - source: /mnt
        target: /etc/traefik/dynamic
        type: bind
