- name: deploy holocrontv swarm service
  hosts: rpi01
  remote_user: pi
  become: yes
  
  vars_files:
    - ~/git/HomeLab/vault.yml

  vars:
    ansible_ssh_pass: "{{ remote_pass }}"

  tasks:
    - name: holocrontv swarm service
      docker_swarm_service:
        name: holocrontv
        image:  clintcolding/holocrontv
        networks:
          - traefik
        replicas: 1
        labels:
          #---- 80 Entry ----#
          traefik.http.routers.holocrontv.rule: "Host(`holocron.clintcolding.com`)"
          traefik.http.routers.holocrontv.entrypoints: "web"
          traefik.http.routers.holocrontv.middlewares: "holocrontv_redirect"
          #---- 443 Entry ----#
          traefik.http.routers.holocrontvsecure.rule: "Host(`holocron.clintcolding.com`)"
          traefik.http.routers.holocrontvsecure.entrypoints: "websecure"
          #---- Create the middleware "redirect" used on 80 entry ----#
          traefik.http.middlewares.holocrontv_redirect.redirectscheme.scheme: "https"
          #---- Expose container port 80 ----#
          traefik.http.services.holocrontv-service.loadbalancer.server.port: "80"
          #---- ACME config for websecure router ----#
          traefik.http.routers.holocrontvsecure.tls.certresolver: "httpchallenge"
          
