- hosts: rpi01
  remote_user: pi
  become: yes
  
  vars_files:
    - ~/git/HomeLab/vault.yml

  vars:
    ansible_ssh_pass: "{{ remote_pass }}"

  tasks:
    - name: create homeassistant volume
      docker_volume:
        name: homeassistant-config

    - name: create homeassistant service
      docker_swarm_service:
        name: homeassistant
        image: homeassistant/home-assistant:stable
        replicas: 1
        placement:
          constraints:
            - node.hostname == rpi02
        networks:
          - traefik
        labels:
          traefik.http.routers.homeassistant.rule: "Host(`home.thecoldings.com`)"
          traefik.http.services.homeassistant-service.loadbalancer.server.port: "8123"
          traefik.http.routers.homeassistant.entrypoints: "websecure"
          traefik.http.routers.homeassistant.tls.certresolver: "httpchallenge"
        mounts:
          - source: homeassistant-config
            target: /config
            type: volume