- name: Mount NFS Storage
  hosts: docker
  remote_user: pi
  become: yes
  
  vars_files:
    - ~/git/HomeLab/vault.yml

  vars:
    ansible_ssh_pass: "{{ remote_pass }}"

  tasks:
    - name: Create mount dir
      file:
        path: /mnt/prometheus
        state: directory

    - name: 
      mount:
        path: /mnt/prometheus
        src: 192.168.1.99:/mnt/prometheus
        fstype: nfs
        opts: defaults
        passno: 0
        dump: 0
        state: mounted

    - name: Create mount dir
      file:
        path: /mnt/grafana
        state: directory
  
    - name: 
      mount:
        path: /mnt/grafana
        src: 192.168.1.99:/mnt/grafana
        fstype: nfs
        opts: defaults
        passno: 0
        dump: 0
        state: mounted